# Generated by Django 5.1.6 on 2025-04-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='excerpt',
        ),
        migrations.AddField(
            model_name='blog',
            name='subtitle',
            field=models.CharField(default='Subtitulo por defecto', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='blog_images/'),
            preserve_default=False,
        ),
    ]
